# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

def even_fibs_sum(max_value)
  fibs_generator(max_value).select { |fib| fib.even? }.reduce(:+)
end

def fibs_generator(max_value)
  fibs = [1, 2]

  while fibs[-2] + fibs[-1] <= max_value
    fibs.push(fibs[-2] + fibs[-1])
  end

  fibs
end
